# Generated by Django 3.1 on 2020-08-11 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=120, verbose_name='Codigo')),
                ('Nombre', models.CharField(max_length=120, verbose_name='Nombre del curso')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=45, verbose_name='Nombre del departamento')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=120, verbose_name='Estado de finalizaciòn')),
            ],
            options={
                'verbose_name': 'Estado de finalizaciòn',
                'verbose_name_plural': 'Estados de finalizaciòn',
            },
        ),
        migrations.CreateModel(
            name='operador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=45, verbose_name='Nombre de la operadora')),
            ],
            options={
                'verbose_name': 'Operador',
                'verbose_name_plural': 'Operadores',
            },
        ),
        migrations.CreateModel(
            name='tipodecurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=120, verbose_name='Tipo de curso')),
            ],
            options={
                'verbose_name': 'Tipo de curso',
                'verbose_name_plural': 'Tipos de cursos',
            },
        ),
        migrations.CreateModel(
            name='profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=45)),
                ('Apellido', models.CharField(max_length=45)),
                ('CorreoInstitucional', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Institucional')),
                ('CorreoPersonal', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Personal')),
                ('Departamentoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciencias_app.departamento')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
            },
        ),
        migrations.CreateModel(
            name='operador_profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Telefono', models.CharField(max_length=45, verbose_name='Numero de telefono')),
                ('OPeradorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciencias_app.operador')),
                ('Profesorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciencias_app.profesor')),
            ],
            options={
                'verbose_name': 'OPerador - Profesor',
                'verbose_name_plural': 'Operadores - Profesores',
            },
        ),
        migrations.CreateModel(
            name='curso_profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fechainicio', models.DateField(verbose_name='Fecha de inicio')),
                ('Fechafinal', models.DateField(verbose_name='Fecha de finalizacion')),
                ('Cohorte', models.IntegerField(verbose_name='Cohorte')),
                ('Cursoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciencias_app.curso')),
                ('Estadoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciencias_app.estado')),
                ('Profesorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciencias_app.profesor')),
            ],
            options={
                'verbose_name': 'Curso - Profesor',
                'verbose_name_plural': 'Cursos - Profesores',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='Tipodecursoid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciencias_app.tipodecurso'),
        ),
        migrations.CreateModel(
            name='carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=120, verbose_name='carreras')),
                ('Departamentoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciencias_app.departamento')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
    ]
