# Generated by Django 3.1 on 2020-08-11 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ciencias_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='Departamentoid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciencias_app.departamento', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='Tipodecursoid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciencias_app.tipodecurso', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='curso_profesor',
            name='Cursoid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciencias_app.curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='curso_profesor',
            name='Estadoid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciencias_app.estado', verbose_name='Estado de finalizacion'),
        ),
        migrations.AlterField(
            model_name='curso_profesor',
            name='Profesorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciencias_app.profesor', verbose_name='Profesor'),
        ),
        migrations.AlterField(
            model_name='operador_profesor',
            name='OPeradorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciencias_app.operador', verbose_name='Operadora'),
        ),
        migrations.AlterField(
            model_name='operador_profesor',
            name='Profesorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciencias_app.profesor', verbose_name='Profesor'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='Departamentoid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciencias_app.departamento', verbose_name='Departamento'),
        ),
    ]
