# Generated by Django 3.1 on 2020-08-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciencias_app', '0003_auto_20200812_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='operador_profesor',
            name='Fechacreacion',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de creacion'),
        ),
    ]
