# Generated by Django 3.1 on 2020-08-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciencias_app', '0006_auto_20200812_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='Fechamodificacion',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha de modificacion'),
        ),
    ]
